### ISSUE TITLE
Cloud profiler in GKE (with Istio mesh) fails with 426 - Upgrade Required error

### ISSUE THREAD

**Issue by rravi-sift** [GoogleCloudPlatform/cloud-profiler-java#47]
Hi,

We are using `cloud-profiler-java-agent_20220620_RC00` version and it fails to upload profiles with error

```
I0627 00:08:15.567804  1318 throttler_api.cc:306] Creating a new profile via profiler service
i=0
E0627 00:08:16.590281  1318 throttler_api.cc:85] GRPC: src/core/lib/security/credentials/oauth2/oauth2_credentials.cc:154 Call to http server ended with error 426 [].
W0627 00:08:16.590461  1318 throttler_api.cc:407] Failed to create profile, will retry: 14 (Error occurred when fetching oauth2 token.)
```

Thanks to Google support, we have identified the root cause to be that because Istio service mesh intercepts and returns 426 when the profiler makes a HTTP1.0 call to oauth2 service. gRPC library has [patched](https://github.com/grpc/grpc/pull/29238) the httpcli to use HTTP 1.1 in [v1.46.0](https://github.com/grpc/grpc/releases/tag/v1.46.0). But I am still running into this issue when using the agent. Any advice?

**Comment by punya** [comment]
Hi @rravi-sift, sorry for the long wait.

It looks like the Cloud Profiler agent is using [gRPC v1.28.1](https://github.com/GoogleCloudPlatform/cloud-profiler-java/blob/18314482259f55c4405b98d8ad1d278cc1181f12/Dockerfile#L92), which doesn't have the HTTP 1.1 patch you mentioned. Are you using a custom binary that's been compiled against gRPC >= 1.46.0 instead?

It would be helpful if you could link to any existing Google customer support tickets so that I don't have to bug you for information you might have provided earlier.

**Comment by rravi-sift** [comment]
Sorry for not getting back to you sooner, @punya. We are using the agent from https://storage.googleapis.com/cloud-profiler/java/cloud-profiler-java-agent_20220905_RC00.tar.gz

We could workaround this issue by setting a flag to support HTTP 1.0 in Istio. Closing the issue since a workaround exists.
```
            - name: ISTIO_META_HTTP10
              value: "1"
```
